language: python
python:
  - 2.7

sudo: false

# command to install dependencies
install: 
  - conda install --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib cython ipython
  - pip install sphinx
  - pip install -r requirements.txt
  - pip install git+https://github.com/simpeg/simpeg.git@v0.1.3

# command to run tests
script: sphinx-build -nW -b html -d _build/doctrees . _build/html

# Flags used here, not in `make html`:
#  -n   Run in nit-picky mode. Currently, this generates warnings for all missing references.
#  -W   Turn warnings into errors. This means that the build stops at the first warning and sphinx-build exits with exit status 1.

notifications:
  email:
    - lindseyheagy@gmail.com