application: emgeosci
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.*\.css)
  mime_type: text/css
  static_files: _build/html/\1
  upload: _build/html/(.*\.css)

- url: /(.*\.html)
  mime_type: text/html
  static_files: _build/html/\1
  upload: _build/html/(.*\.html)

- url: /_images/(.*\.(gif|png|jpg|ico))
  static_files: _build/html/_images/\1
  upload: _build/html/_images(.*\.(gif|png|jpg|ico))

- url: /
  static_files: _build/html/index.html
  upload: _build/html/index.html

- url: /(.*\.(gif|png|jpg|ico|js|css|html))
  static_files:  _build/html/\1
  upload: _build/html/(.*\.(gif|png|jpg|ico|js|css|html))

- url: /
  script: emgeosci.app

- url: /.*
  static_files: _build/html/error.html
  upload: _build/html/error.html


libraries:
- name: webapp2
  version: "2.5.2"
- name: PIL
  version: "1.1.7"
- name: numpy
  version: "latest"
- name: jinja2
  version: "latest"
